[project]
name = "ollama-downloader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Anirban Basu", email = "anirbanbasu@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
ollama-downloader = "ollama_downloader:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
